version: "3.2"
services:
  inspec:
    build: .
    image: inspec
    environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        #- AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    command: inspec exec data -t aws://
    volumes:
      - type: bind
        source: ./
        target: /data
